# Generated by Django 2.1.1 on 2018-09-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_auto_20180925_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
