# Generated by Django 2.1.1 on 2018-09-29 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0008_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
