# Generated by Django 2.1.1 on 2018-09-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0009_share_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.IntegerField(default=0),
        ),
    ]
