# Generated by Django 2.1.1 on 2018-09-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0010_profile_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notifications',
            field=models.IntegerField(default=1),
        ),
    ]
