# Generated by Django 2.1.1 on 2018-10-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0011_auto_20180929_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notificationsString',
            field=models.TextField(blank=True, null=True),
        ),
    ]
