# Generated by Django 2.1.1 on 2018-10-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0012_profile_notificationsstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notificationsString',
            field=models.TextField(default=''),
        ),
    ]
