# Generated by Django 2.1.1 on 2018-10-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0014_auto_20181005_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videoname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
