# Generated by Django 2.1.2 on 2018-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0015_post_videoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credibilityscore',
            field=models.IntegerField(default=0),
        ),
    ]
