# Generated by Django 2.1.2 on 2018-10-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0017_auto_20181007_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagename',
            field=models.TextField(default='image0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credibilityscore',
            field=models.FloatField(default=0),
        ),
    ]
