# Generated by Django 2.1.2 on 2018-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0018_auto_20181010_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
