# Generated by Django 2.1.2 on 2018-10-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0019_share_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sharecomment',
            field=models.TextField(default=''),
        ),
    ]
