# Generated by Django 2.1.3 on 2019-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0027_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='videolabels',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='labels',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='withdrawdata',
            field=models.BooleanField(default=False, verbose_name='I wish to have my data withdrawn'),
        ),
    ]
