# Generated by Django 2.1.3 on 2019-03-19 17:07

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0028_auto_20190213_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
