# Generated by Django 2.1.7 on 2019-03-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0031_auto_20190321_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login_count',
        ),
    ]
