# Generated by Django 2.1.7 on 2019-04-01 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0032_remove_profile_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral',
            field=models.UUIDField(blank=True, null=True, default=uuid.uuid4, editable=False),
        ),
    ]
