# Generated by Django 2.1.7 on 2019-04-01 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0033_profile_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
