# Generated by Django 2.1.7 on 2019-04-01 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0034_auto_20190401_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
