# Generated by Django 2.1.7 on 2019-04-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0035_auto_20190401_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral',
            field=models.UUIDField(blank=True, default='', editable=False, null=True),
        ),
    ]
