# Generated by Django 2.1.7 on 2019-03-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20180918_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
